
package Dialogos;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import Clases.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;


public class AgregarUser extends javax.swing.JDialog {

    private int idGenerado;

    public AgregarUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalAgregar = new javax.swing.JPanel();
        btnRegresarCajero = new javax.swing.JButton();
        EtAddUser = new javax.swing.JLabel();
        etNameUser = new javax.swing.JLabel();
        TextFielNameUser = new javax.swing.JTextField();
        etEdadUser = new javax.swing.JLabel();
        textFechaNacimiento = new javax.swing.JTextField();
        EtNumeroTel = new javax.swing.JLabel();
        textNumeroTel = new javax.swing.JTextField();
        etDireccion1 = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        etCorreoElectronico = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        etPuesto = new javax.swing.JLabel();
        Puestos = new javax.swing.JComboBox<>();
        etFechaRegistro = new javax.swing.JLabel();
        textFechaRegistro = new javax.swing.JTextField();
        etIdUser = new javax.swing.JLabel();
        et_idGenerado = new javax.swing.JLabel();
        etTurno = new javax.swing.JLabel();
        Turnos = new javax.swing.JComboBox<>();
        etSueldo = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        BtnAgregarUsuario = new javax.swing.JButton();
        btnGenerarId = new javax.swing.JButton();
        EtFondoAgregar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Usuario");
        setBackground(new java.awt.Color(200, 173, 123));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipalAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanelPrincipalAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRegresarCajero.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresarCajero.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        btnRegresarCajero.setText("Regresar");
        btnRegresarCajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarCajeroMouseClicked(evt);
            }
        });
        btnRegresarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCajeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 130, 40));

        EtAddUser.setBackground(new java.awt.Color(204, 204, 204));
        EtAddUser.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        EtAddUser.setText("AGREGAR NUEVO USUARIO");
        EtAddUser.setOpaque(true);
        getContentPane().add(EtAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 360, 50));

        etNameUser.setBackground(new java.awt.Color(204, 204, 204));
        etNameUser.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etNameUser.setText("INGRESE SU NOMBRE COMPLETO :");
        etNameUser.setOpaque(true);
        getContentPane().add(etNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 30));

        TextFielNameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFielNameUserActionPerformed(evt);
            }
        });
        getContentPane().add(TextFielNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 320, 30));

        etEdadUser.setBackground(new java.awt.Color(204, 204, 204));
        etEdadUser.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etEdadUser.setText("INGRESE SU  FECHA DE NACIMIENTO: ");
        etEdadUser.setOpaque(true);
        getContentPane().add(etEdadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, 30));

        textFechaNacimiento.setText("DIA/MES/AÑO");
        textFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(textFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 120, 30));

        EtNumeroTel.setBackground(new java.awt.Color(204, 204, 204));
        EtNumeroTel.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        EtNumeroTel.setText("INGRESE SU NUMERO TELEFONICO: ");
        EtNumeroTel.setOpaque(true);
        getContentPane().add(EtNumeroTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 30));

        textNumeroTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroTelActionPerformed(evt);
            }
        });
        getContentPane().add(textNumeroTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, 30));

        etDireccion1.setBackground(new java.awt.Color(204, 204, 204));
        etDireccion1.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etDireccion1.setText("INGRESE SU DIRECCIÓN : ");
        etDireccion1.setOpaque(true);
        getContentPane().add(etDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, 30));
        getContentPane().add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 320, 30));

        etCorreoElectronico.setBackground(new java.awt.Color(204, 204, 204));
        etCorreoElectronico.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etCorreoElectronico.setText("INGRESE SU CORREO ELECTRONICO: ");
        etCorreoElectronico.setOpaque(true);
        getContentPane().add(etCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, 30));

        textCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(textCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 320, 30));

        etPuesto.setBackground(new java.awt.Color(204, 204, 204));
        etPuesto.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etPuesto.setText("INGRESE EL PUESTO QUE TENDRA: ");
        etPuesto.setOpaque(true);
        getContentPane().add(etPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 30));

        Puestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAJERO", "MESERO", "COCINERO", "LIMPIEZA GENERAL", "LAVALOZA", "GERENTE " }));
        Puestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuestosActionPerformed(evt);
            }
        });
        getContentPane().add(Puestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 180, 30));

        etFechaRegistro.setBackground(new java.awt.Color(204, 204, 204));
        etFechaRegistro.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etFechaRegistro.setText("INGRESE LA FECHA DEL REGISTRO: ");
        etFechaRegistro.setOpaque(true);
        getContentPane().add(etFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 210, 30));

        textFechaRegistro.setText("DIA/MES/AÑO");
        textFechaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(textFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, 30));

        etIdUser.setBackground(new java.awt.Color(204, 204, 204));
        etIdUser.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etIdUser.setText("      ID DE USUARIO: ");
        etIdUser.setOpaque(true);
        getContentPane().add(etIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 130, 40));

        et_idGenerado.setBackground(new java.awt.Color(255, 255, 255));
        et_idGenerado.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        et_idGenerado.setOpaque(true);
        getContentPane().add(et_idGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 130, 40));

        etTurno.setBackground(new java.awt.Color(204, 204, 204));
        etTurno.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etTurno.setText("TURNO LABORAL");
        etTurno.setOpaque(true);
        getContentPane().add(etTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 130, 40));

        Turnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", " " }));
        getContentPane().add(Turnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 100, 40));

        etSueldo.setBackground(new java.awt.Color(204, 204, 204));
        etSueldo.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etSueldo.setText("INGRESA EL SUELDO SEMANAL:");
        etSueldo.setOpaque(true);
        getContentPane().add(etSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, 40));

        jTextSueldo.setText("$0.00");
        getContentPane().add(jTextSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 160, 40));

        BtnAgregarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        BtnAgregarUsuario.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnAgregarUsuario.setText("Agregar");
        BtnAgregarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 150, 60));

        btnGenerarId.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerarId.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnGenerarId.setText("GENERAR EL ID ");
        btnGenerarId.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnGenerarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarIdActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 120, 40));

        EtFondoAgregar.setBackground(new java.awt.Color(200, 173, 123));
        EtFondoAgregar.setOpaque(true);
        getContentPane().add(EtFondoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarCajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarCajeroMouseClicked

    }//GEN-LAST:event_btnRegresarCajeroMouseClicked

    private void btnRegresarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCajeroActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarCajeroActionPerformed

    private void TextFielNameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFielNameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFielNameUserActionPerformed

    private void BtnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarUsuarioActionPerformed
       String nombreUser = TextFielNameUser.getText();
        String fechaNacimientoUser = textFechaNacimiento.getText();
        String numeroTelefonoUser = textNumeroTel.getText();
        String direccionUser = textDireccion.getText();
        String correoUser = textCorreo.getText();
        String puestoSeleccionado = Puestos.getSelectedItem().toString();
        String fechaRegistro = textFechaRegistro.getText();
        String idUser = et_idGenerado.getText(); // Obtener el ID generado desde la etiqueta
        String TurnoUser = Turnos.getSelectedItem().toString();
        String sueldoUser = jTextSueldo.getText();

        // Verificar que todos los campos estén llenos
        if (nombreUser.isEmpty() || fechaNacimientoUser.isEmpty() || numeroTelefonoUser.isEmpty() || direccionUser.isEmpty() || correoUser.isEmpty()
                || puestoSeleccionado.isEmpty() || fechaRegistro.isEmpty() || idUser.isEmpty() || TurnoUser.isEmpty() || sueldoUser.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Todos los campos son obligatorios");
            return;
        }

        // Crear una instancia de Empleado con los datos ingresados
        Empleado empleadoNuevo = new Empleado(nombreUser, fechaNacimientoUser, direccionUser, numeroTelefonoUser, correoUser, fechaRegistro);
        empleadoNuevo.setNombre(nombreUser);
        empleadoNuevo.setNumeroTel(numeroTelefonoUser);
        empleadoNuevo.setPuesto(puestoSeleccionado);
        empleadoNuevo.setFechaRegistro(fechaRegistro);
        empleadoNuevo.setIdEmpleado(Integer.parseInt(idUser)); // Utilizar el ID obtenido desde la etiqueta
        empleadoNuevo.setTurno(TurnoUser);
        empleadoNuevo.setSalario(sueldoUser);

        // Escribir los datos del nuevo empleado en el archivo
        FileWriter fileWriter = null;
        BufferedWriter bufferedWriter = null;
        try {
            // Abrir el archivo en modo append (agregar al final)
            fileWriter = new FileWriter("empleados.txt", true);
            bufferedWriter = new BufferedWriter(fileWriter);

            // Escribir los datos del empleado en el archivo
            bufferedWriter.write(empleadoNuevo.toString());
            bufferedWriter.newLine();

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Empleado agregado correctamente");

            // Limpiar los campos del formulario
            limpiarCampos();

        } catch (IOException e) {
            // Mostrar un mensaje de error si ocurre un problema al escribir en el archivo
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar los datos del empleado", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar el BufferedWriter y FileWriter
            if (bufferedWriter != null) {
                try {
                    bufferedWriter.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (fileWriter != null) {
                try {
                    fileWriter.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_BtnAgregarUsuarioActionPerformed
    private void limpiarCampos() {
    TextFielNameUser.setText("");
    textFechaNacimiento.setText("");
    textNumeroTel.setText("");
    textDireccion.setText("");
    textCorreo.setText("");
    Puestos.setSelectedIndex(0);
    textFechaRegistro.setText("");
    et_idGenerado.setText("");
    Turnos.setSelectedIndex(0);
    jTextSueldo.setText("");
    
}
   
 private int generarIdAleatorio() {
    // Generar un id aleatorio, por ejemplo, un número entre 1000 y 9999
    return (int) (Math.random() * 9000) + 1000;
}

    
    private void textFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaNacimientoActionPerformed
        String fechaTexto = textFechaNacimiento.getText();

       // Validar si la fecha tiene el formato correcto
     if (Empleado.validarFecha(fechaTexto)) {
         // Si la fecha tiene el formato correcto
         // Aquí puedes realizar acciones con la fecha, por ejemplo, almacenarla en una variable
         System.out.println("Fecha de nacimiento ingresada: " + fechaTexto);
     } else {
         // Si la fecha no tiene el formato correcto, mostrar un mensaje de error
         JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Por favor, ingrese la fecha en formato dd/MM/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_textFechaNacimientoActionPerformed

    private void textNumeroTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroTelActionPerformed

    private void textCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCorreoActionPerformed

    private void textFechaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaRegistroActionPerformed
        String fechaTexto = textFechaRegistro.getText();
        
       // Validar si la fecha tiene el formato correcto
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
         dateFormat.setLenient(false); // Para que no permita fechas inválidas

         try {
             Date fecha = dateFormat.parse(fechaTexto);
             // Aquí puedes realizar acciones con la fecha, por ejemplo, almacenarla en una variable
             System.out.println("Fecha de registro ingresada: " + fecha);
         } catch (ParseException ex) {
             // Si la fecha no tiene el formato correcto, mostrar un mensaje de error
             JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Por favor, ingrese la fecha en formato dd/MM/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_textFechaRegistroActionPerformed

    private void btnGenerarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarIdActionPerformed
        // Generar un nuevo ID aleatorio
    idGenerado = generarIdAleatorio();
    
    // Mostrar el ID generado en la etiqueta
    et_idGenerado.setText(String.valueOf(idGenerado));
    }//GEN-LAST:event_btnGenerarIdActionPerformed

    private void PuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuestosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarUsuario;
    private javax.swing.JLabel EtAddUser;
    private javax.swing.JLabel EtFondoAgregar;
    private javax.swing.JLabel EtNumeroTel;
    private javax.swing.JPanel PanelPrincipalAgregar;
    private javax.swing.JComboBox<String> Puestos;
    private javax.swing.JTextField TextFielNameUser;
    private javax.swing.JComboBox<String> Turnos;
    private javax.swing.JButton btnGenerarId;
    private javax.swing.JButton btnRegresarCajero;
    private javax.swing.JLabel etCorreoElectronico;
    private javax.swing.JLabel etDireccion1;
    private javax.swing.JLabel etEdadUser;
    private javax.swing.JLabel etFechaRegistro;
    private javax.swing.JLabel etIdUser;
    private javax.swing.JLabel etNameUser;
    private javax.swing.JLabel etPuesto;
    private javax.swing.JLabel etSueldo;
    private javax.swing.JLabel etTurno;
    private javax.swing.JLabel et_idGenerado;
    private javax.swing.JTextField jTextSueldo;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textFechaNacimiento;
    private javax.swing.JTextField textFechaRegistro;
    private javax.swing.JTextField textNumeroTel;
    // End of variables declaration//GEN-END:variables
}
