package Dialogos;

import Interfaces2.InterfazEmpleados;

/**
 *
 * @author carmi
 */
public class Ayuda extends javax.swing.JDialog {

    /**
     * Creates new form Ayuda
     */
    public Ayuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        ScrollInformacion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TituloInfo = new javax.swing.JLabel();
        BtnCerrarInfo = new javax.swing.JButton();
        etPrincipalInformacon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Info");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Para dudas o mayor informacion sobre el uso \ndel software puede ponerse en contacto con \nel soporte tecnico o directamente con el \nprogramador al correo:\nEricdh221@gmail.com\nO al numero telefonico:\n2222175420\nPara dudas sobre la empresa comuniquese al \ncorre:\nnombreempresa@gmail.com\n                           ¡GRACIAS!\n");
        ScrollInformacion.setViewportView(jTextArea1);

        getContentPane().add(ScrollInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 280, 200));

        TituloInfo.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        TituloInfo.setText("INFORMACION ");
        getContentPane().add(TituloInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, 30));

        BtnCerrarInfo.setBackground(new java.awt.Color(204, 204, 204));
        BtnCerrarInfo.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnCerrarInfo.setText("CERRAR");
        BtnCerrarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarInfoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerrarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, 110, 30));

        etPrincipalInformacon.setBackground(new java.awt.Color(200, 173, 123));
        etPrincipalInformacon.setOpaque(true);
        getContentPane().add(etPrincipalInformacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarInfoActionPerformed
        InterfazEmpleados regresar = new InterfazEmpleados();
        regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCerrarInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ayuda dialog = new Ayuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarInfo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JScrollPane ScrollInformacion;
    private javax.swing.JLabel TituloInfo;
    private javax.swing.JLabel etPrincipalInformacon;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
