package Dialogos;


import Clases.Cajero;
import Excepciones.ExcepcionRestaurante;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class D_Cajero extends javax.swing.JDialog {
    
    Cajero operacion = new Cajero();
    
    public D_Cajero(java.awt.Frame parent, boolean modal, String total) {
        super(parent, modal);
        initComponents();
        etTotalNum.setText(total);
        this.setLocationRelativeTo(null);
        
//        etTotalNum.setText(total);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalCajero = new javax.swing.JPanel();
        panelTituloCajero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnRegresarCajero = new javax.swing.JButton();
        etTotalpagar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etTotalNum = new javax.swing.JLabel();
        campoPago = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        etCambioRes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cajero");

        panelPrincipalCajero.setBackground(new java.awt.Color(200, 173, 123));

        panelTituloCajero.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CAJERO");

        javax.swing.GroupLayout panelTituloCajeroLayout = new javax.swing.GroupLayout(panelTituloCajero);
        panelTituloCajero.setLayout(panelTituloCajeroLayout);
        panelTituloCajeroLayout.setHorizontalGroup(
            panelTituloCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloCajeroLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloCajeroLayout.setVerticalGroup(
            panelTituloCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloCajeroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelBotones.setBackground(new java.awt.Color(153, 153, 153));

        btnRegresarCajero.setText("Regresar");
        btnRegresarCajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarCajeroMouseClicked(evt);
            }
        });
        btnRegresarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnRegresarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        etTotalpagar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etTotalpagar.setText("El total de tu orden fue: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ingresa el pago:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Su cambio es de:");

        etTotalNum.setBackground(new java.awt.Color(255, 255, 255));
        etTotalNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etTotalNum.setOpaque(true);

        campoPago.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPagoActionPerformed(evt);
            }
        });

        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        btnPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPagarKeyPressed(evt);
            }
        });

        etCambioRes.setBackground(new java.awt.Color(255, 255, 255));
        etCambioRes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etCambioRes.setOpaque(true);

        javax.swing.GroupLayout panelPrincipalCajeroLayout = new javax.swing.GroupLayout(panelPrincipalCajero);
        panelPrincipalCajero.setLayout(panelPrincipalCajeroLayout);
        panelPrincipalCajeroLayout.setHorizontalGroup(
            panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTituloCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalCajeroLayout.createSequentialGroup()
                .addGroup(panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalCajeroLayout.createSequentialGroup()
                        .addGroup(panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalCajeroLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(etTotalpagar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalCajeroLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincipalCajeroLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etCambioRes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalCajeroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(panelPrincipalCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrincipalCajeroLayout.setVerticalGroup(
            panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalCajeroLayout.createSequentialGroup()
                .addComponent(panelTituloCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etTotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPago))
                .addGap(18, 18, 18)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelPrincipalCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(etCambioRes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
//     String totalText = etTotalNum.getText();
//    totalText = totalText.replaceAll("[^\\d.]", "");
//
//    double total = 0.0;
//    try {
//        total = Double.parseDouble(totalText);
//    } catch (NumberFormatException e) {
//        System.out.println("Error al convertir");
//    }
//
//    double pagoCliente = 0.0;
//    try {
//        pagoCliente = Double.parseDouble(campoPago.getText());
//    } catch (NumberFormatException e) {
//        System.out.println("Error al convertir");
//    }
//
//    try {
//        if (pagoCliente == 0.0) {
//            throw new ExcepcionRestaurante("El campo de pago del cliente está vacío");
//        }
//
//        operacion.cobrar(total, pagoCliente);
//
//        double cambioPago = operacion.cambiopago;
//
//        String cambioPagoMoneda = cMoneda(cambioPago);
//        etCambioRes.setText(cambioPagoMoneda);
//    } catch (ExcepcionRestaurante e) {
//        JOptionPane.showMessageDialog(this, "Ingresa una cantidad valida", "Error", JOptionPane.ERROR_MESSAGE);
//    }
    String totalText = etTotalNum.getText();
    totalText = totalText.replaceAll("[^\\d.]", "");

    double total = 0.0;
    try {
        total = Double.parseDouble(totalText);
    } catch (NumberFormatException e) {
        System.out.println("Error al convertir");
    }

    double pagoCliente = 0.0;
    try {
        pagoCliente = Double.parseDouble(campoPago.getText());
    } catch (NumberFormatException e) {
        System.out.println("Error al convertir");
    }

    try {
        if (pagoCliente == 0.0) {
            throw new ExcepcionRestaurante("El campo de pago del cliente está vacío");
        }
       
        if (total > pagoCliente) {
        throw new ExcepcionRestaurante("El pago del cliente es insuficiente");
    }

        operacion.cobrar(total, pagoCliente);

        double cambioPago = operacion.cambiopago;

        String cambioPagoMoneda = cMoneda(cambioPago);
        etCambioRes.setText(cambioPagoMoneda);

        // Imprimir mensaje de pago exitoso
        JOptionPane.showMessageDialog(this, "CAJERO: Pago realizado con éxito", "CAJERO", JOptionPane.INFORMATION_MESSAGE);
    } catch (ExcepcionRestaurante e) {
        JOptionPane.showMessageDialog(this, "Ingresa una cantidad válida", "Cajero Error", JOptionPane.ERROR_MESSAGE);
    }
    
    
    }//GEN-LAST:event_btnPagarActionPerformed
    
    public String cMoneda(double precio) {
        return "$" + Math.round(precio * 100.0) / 100.0 + "MXN";
    }
    
    private void btnRegresarCajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarCajeroMouseClicked

    }//GEN-LAST:event_btnRegresarCajeroMouseClicked

    private void campoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPagoActionPerformed
       
    }//GEN-LAST:event_campoPagoActionPerformed

    private void btnRegresarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCajeroActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarCajeroActionPerformed

    private void btnPagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPagarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(null, "PAGO EXITOSO");
        }
    }//GEN-LAST:event_btnPagarKeyPressed
//    public void setEtiquetaTotal(JLabel etiqueta) {
//    this.etiquetaTotal = etiqueta;
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_Cajero dialog = new D_Cajero(new javax.swing.JFrame(), true, null);
//                dialog.setEtiquetaTotal(ettotal);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRegresarCajero;
    private javax.swing.JTextField campoPago;
    private javax.swing.JLabel etCambioRes;
    private javax.swing.JLabel etTotalNum;
    private javax.swing.JLabel etTotalpagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPrincipalCajero;
    private javax.swing.JPanel panelTituloCajero;
    // End of variables declaration//GEN-END:variables
}