package Dialogos;

import Interfaces2.InterfazEmpleados;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author carmi
 */
public class QuejasSugerencias extends javax.swing.JDialog {

    /**
     * Creates new form QuejasSugerencias
     */
    public QuejasSugerencias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalqs = new javax.swing.JPanel();
        etTituloqs = new javax.swing.JLabel();
        etQuejas = new javax.swing.JLabel();
        textQuejas = new javax.swing.JTextField();
        etSugerencias = new javax.swing.JLabel();
        textSugerencias = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        etPrincipalQS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipalqs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etTituloqs.setBackground(new java.awt.Color(204, 204, 204));
        etTituloqs.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        etTituloqs.setText("QUEJAS Y SUGERENCIAS");
        etTituloqs.setOpaque(true);
        PanelPrincipalqs.add(etTituloqs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 470, 60));

        etQuejas.setBackground(new java.awt.Color(204, 204, 204));
        etQuejas.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        etQuejas.setText("SI TIENE ALGUNA QUEJA INGRESA AQUI: ");
        etQuejas.setOpaque(true);
        PanelPrincipalqs.add(etQuejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 310, 50));
        PanelPrincipalqs.add(textQuejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 340, 120));

        etSugerencias.setBackground(new java.awt.Color(204, 204, 204));
        etSugerencias.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        etSugerencias.setText("SI TIENE ALGUNA SUGERENCIA INGRESE AQUI: ");
        etSugerencias.setOpaque(true);
        PanelPrincipalqs.add(etSugerencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 50));
        PanelPrincipalqs.add(textSugerencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 340, 130));

        btnCerrar.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrar.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        PanelPrincipalqs.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 120, 60));

        btnEnviar.setBackground(new java.awt.Color(204, 204, 204));
        btnEnviar.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        PanelPrincipalqs.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 130, 50));

        etPrincipalQS.setBackground(new java.awt.Color(200, 173, 123));
        etPrincipalQS.setOpaque(true);
        PanelPrincipalqs.add(etPrincipalQS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        getContentPane().add(PanelPrincipalqs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        InterfazEmpleados regresar = new InterfazEmpleados();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
         String quejasMandar = textQuejas.getText();
    String sugerenciasMandar = textSugerencias.getText();
    
    // Verificar si al menos uno de los campos tiene texto
    if (!quejasMandar.isEmpty() || !sugerenciasMandar.isEmpty()) {
        FileWriter escribirArchivo = null;
        BufferedWriter bufferEscribirAr = null;

        try {
            escribirArchivo = new FileWriter("quejas_y_sugerencias.txt", true);
            bufferEscribirAr = new BufferedWriter(escribirArchivo);

            // Escribir las quejas y sugerencias en el archivo
            if (!quejasMandar.isEmpty()) {
                bufferEscribirAr.write("Quejas: " + quejasMandar);
                bufferEscribirAr.newLine();
            }
            if (!sugerenciasMandar.isEmpty()) {
                bufferEscribirAr.write("Sugerencias: " + sugerenciasMandar);
                bufferEscribirAr.newLine();
            }

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Quejas y/o sugerencias enviadas correctamente");
            limpiarDatos();

            // Limpiar los campos después de enviar
            textQuejas.setText("");
            textSugerencias.setText("");

        } catch (IOException e) {
            // Mostrar un mensaje de error si ocurre un problema al escribir en el archivo
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar las quejas y sugerencias", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar el BufferedWriter y FileWriter
            if (bufferEscribirAr != null) {
                try {
                    bufferEscribirAr.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (escribirArchivo != null) {
                try {
                    escribirArchivo.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    } else {
        // Mostrar un mensaje de error si ninguno de los campos tiene texto
        JOptionPane.showMessageDialog(this, "Por favor, ingrese al menos una queja o sugerencia", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEnviarActionPerformed
    private void limpiarDatos(){
        textQuejas.setText("");
        textSugerencias.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipalqs;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel etPrincipalQS;
    private javax.swing.JLabel etQuejas;
    private javax.swing.JLabel etSugerencias;
    private javax.swing.JLabel etTituloqs;
    private javax.swing.JTextField textQuejas;
    private javax.swing.JTextField textSugerencias;
    // End of variables declaration//GEN-END:variables
}
