/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces2;

import Dialogos.DialogoInfoRestauran2;
import Dialogos.DialogoCliente2;
import javax.swing.JOptionPane;

/**
 *
 * @author carmi
 */
public class InterfazRestaurante2 extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRestaurante2
     */
    public InterfazRestaurante2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Et_img_Pizza = new javax.swing.JLabel();
        Boton_clientes = new javax.swing.JButton();
        Btn_Menu = new javax.swing.JButton();
        Btn_Orden = new javax.swing.JButton();
        Btn_inf = new javax.swing.JButton();
        Boton_salir = new javax.swing.JButton();
        BtnEmpleados = new javax.swing.JButton();
        PanelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Restaurante Software");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Et_img_Pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LGO.jpg"))); // NOI18N
        Et_img_Pizza.setMaximumSize(new java.awt.Dimension(31, 314));
        Et_img_Pizza.setMinimumSize(new java.awt.Dimension(317, 34));
        PanelPrincipal.add(Et_img_Pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 220, 170));

        Boton_clientes.setBackground(new java.awt.Color(204, 204, 204));
        Boton_clientes.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Boton_clientes.setText("CLIENTES");
        Boton_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMouseClientes(evt);
            }
        });
        Boton_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_clientesActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Boton_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 150, 50));

        Btn_Menu.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Menu.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Btn_Menu.setText("MENÚ");
        Btn_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMouseMenu(evt);
            }
        });
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 150, 50));

        Btn_Orden.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Orden.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Btn_Orden.setText("ORDENES");
        Btn_Orden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMouseOrden(evt);
            }
        });
        Btn_Orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OrdenActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Btn_Orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, 50));

        Btn_inf.setBackground(new java.awt.Color(204, 204, 204));
        Btn_inf.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Btn_inf.setText("INF. RESTAURANTE ");
        Btn_inf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMouseInfo(evt);
            }
        });
        Btn_inf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_infActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Btn_inf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 290, 50));

        Boton_salir.setBackground(new java.awt.Color(204, 204, 204));
        Boton_salir.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Boton_salir.setText("SALIR");
        Boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_salirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(Boton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 150, 40));

        BtnEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        BtnEmpleados.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        BtnEmpleados.setText("EMPLEADOS");
        BtnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmpleadosActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BtnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 200, 50));

        PanelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInterfazRestaurante.jpg"))); // NOI18N
        PanelFondo.setMaximumSize(new java.awt.Dimension(798, 900));
        PanelPrincipal.add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_salirActionPerformed
         if(JOptionPane.showConfirmDialog(this,"¿SEGURO QUE QUIERES SALIR?","SALIR"
                ,JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_Boton_salirActionPerformed

    private void Btn_OrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OrdenActionPerformed
       interfazOrden2 orden = new interfazOrden2();
       orden.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Btn_OrdenActionPerformed

    private void Btn_infActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_infActionPerformed
       DialogoInfoRestauran2 info = new DialogoInfoRestauran2(this, true);
        info.setVisible(true);
    }//GEN-LAST:event_Btn_infActionPerformed

    private void Boton_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_clientesActionPerformed
        DialogoCliente2 cliente = new DialogoCliente2(this, true);
        cliente.setVisible(true);
    }//GEN-LAST:event_Boton_clientesActionPerformed

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_MenuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                               
        if(JOptionPane.showConfirmDialog(this,"¿SEGURO QUE QUIERES SALIR?","SALIR"
                ,JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
        System.exit(0);
        }          
    }//GEN-LAST:event_formWindowClosing

    private void BtnMouseOrden(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMouseOrden
       interfazOrden2 orden = new interfazOrden2();
       orden.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnMouseOrden

    private void BtnMouseClientes(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMouseClientes
        DialogoCliente2 cliente = new DialogoCliente2(this, true);
        cliente.setVisible(true);
    }//GEN-LAST:event_BtnMouseClientes

    private void BtnMouseMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMouseMenu
       Menu menu = new Menu();
       menu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnMouseMenu

    private void BtnMouseInfo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMouseInfo
        DialogoInfoRestauran2 info = new DialogoInfoRestauran2(this, true);
        info.setVisible(true);
    }//GEN-LAST:event_BtnMouseInfo

    private void BtnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmpleadosActionPerformed
        InterfazEmpleados empleados = new InterfazEmpleados();
        empleados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnEmpleadosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRestaurante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRestaurante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRestaurante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRestaurante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRestaurante2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_clientes;
    private javax.swing.JButton Boton_salir;
    private javax.swing.JButton BtnEmpleados;
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JButton Btn_Orden;
    private javax.swing.JButton Btn_inf;
    private javax.swing.JLabel Et_img_Pizza;
    private javax.swing.JLabel PanelFondo;
    private javax.swing.JPanel PanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
