
package Interfaces2;

import Dialogos.D_Cajero;

import Clases.Menu;
import Clases.Orden;
import Clases.factura;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
import java.io.IOException;


/**
 *
 * @author carmi
 */
public class interfazOrden2 extends javax.swing.JFrame {

    Menu productos1[];
    String productos[] = {"Hamburguesa Sencilla", "Hamburguesa Doble", "Hamburguesa Hawaiana",
        "Pizza Peperoni", "Pizza Hawaiana", "Pizza de Queso", "Papas Fritas Grandes", "Papas Fritas Medianas",
        "Refresco", "Malteada", "Agua de Sabor","COMBO CLASICO","COMBO TRIO","COMBO FAMILIAR"};
    double precios[] = {36, 60, 45, 100, 130, 89, 25, 15, 18, 35, 12,60,145,240};
    double precio = 0;
    int cantidad = 0;

    DefaultTableModel tablaOrden = new DefaultTableModel();
    ArrayList<factura> listaVentas = new ArrayList<factura>();

    public interfazOrden2() {
        initComponents();
        this.setLocationRelativeTo(null);

        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(productos);
        comboProducto.setModel(comboModel);
        tablaOrden.addColumn("NOMBRE");
        tablaOrden.addColumn("PRECIO U.");
        tablaOrden.addColumn("CANTIDAD");
        tablaOrden.addColumn("TOTAL");
        actualizarTabla();
        calcularPrecio();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalOrden = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarOr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        etPrecio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etPrecios = new javax.swing.JLabel();
        ettotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        spnCantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        etImporte = new javax.swing.JLabel();
        etPrecioImporte = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ORDEN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelPrincipalOrden.setBackground(new java.awt.Color(204, 204, 204));
        panelPrincipalOrden.setAutoscrolls(true);
        panelPrincipalOrden.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 48)); // NOI18N
        jLabel1.setText("ORDEN");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        panelPrincipalOrden.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 890, -1));

        btnRegresarOr.setText("REGRESAR");
        btnRegresarOr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarOrMouseClicked(evt);
            }
        });
        btnRegresarOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarOrActionPerformed(evt);
            }
        });
        panelPrincipalOrden.add(btnRegresarOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 575, 99, 36));

        jLabel2.setBackground(new java.awt.Color(200, 173, 123));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Platillo:");
        jLabel2.setAutoscrolls(true);
        jLabel2.setOpaque(true);
        panelPrincipalOrden.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 106, 89, -1));

        etPrecio.setBackground(new java.awt.Color(200, 173, 123));
        etPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etPrecio.setText("Precio/u:");
        etPrecio.setAutoscrolls(true);
        etPrecio.setOpaque(true);
        panelPrincipalOrden.add(etPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 106, 97, -1));

        jLabel4.setBackground(new java.awt.Color(200, 173, 123));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cantidad:");
        jLabel4.setAutoscrolls(true);
        jLabel4.setOpaque(true);
        panelPrincipalOrden.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 176, -1, -1));

        etPrecios.setBackground(new java.awt.Color(200, 173, 123));
        etPrecios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etPrecios.setText("$0.00 MXM");
        etPrecios.setAutoscrolls(true);
        etPrecios.setOpaque(true);
        panelPrincipalOrden.add(etPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 106, 117, -1));

        ettotal.setBackground(new java.awt.Color(200, 173, 123));
        ettotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ettotal.setText("$0.00 MXM");
        ettotal.setAutoscrolls(true);
        ettotal.setOpaque(true);
        panelPrincipalOrden.add(ettotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 579, 117, -1));

        jLabel7.setBackground(new java.awt.Color(200, 173, 123));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total:");
        jLabel7.setAutoscrolls(true);
        jLabel7.setOpaque(true);
        panelPrincipalOrden.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 579, 97, -1));

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductoActionPerformed(evt);
            }
        });
        panelPrincipalOrden.add(comboProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 108, 201, -1));

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spnCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCantidadStateChanged(evt);
            }
        });
        panelPrincipalOrden.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 178, -1, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        panelPrincipalOrden.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 272, 724, 285));

        etImporte.setBackground(new java.awt.Color(200, 173, 123));
        etImporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etImporte.setText("Precio por cantidad");
        etImporte.setAutoscrolls(true);
        etImporte.setOpaque(true);
        panelPrincipalOrden.add(etImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 176, 198, -1));

        etPrecioImporte.setBackground(new java.awt.Color(200, 173, 123));
        etPrecioImporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etPrecioImporte.setText("$0.00 MXM");
        etPrecioImporte.setAutoscrolls(true);
        etPrecioImporte.setOpaque(true);
        panelPrincipalOrden.add(etPrecioImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 176, 117, -1));

        btnAgregar.setBackground(new java.awt.Color(200, 173, 123));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar a orden");
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelPrincipalOrden.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 218, -1, 36));

        jButton1.setText("Hacer Orden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPrincipalOrden.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 575, 105, 39));

        btnPagar.setText("Cajero");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        panelPrincipalOrden.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 575, 91, 39));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInterfazRestaurante.jpg"))); // NOI18N
        panelPrincipalOrden.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 890, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarOrActionPerformed
        InterfazRestaurante2 regresar = new InterfazRestaurante2();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarOrActionPerformed

    private void btnRegresarOrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarOrMouseClicked
        InterfazRestaurante2 regresar = new InterfazRestaurante2();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarOrMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, "¿SEGURO QUE QUIERES SALIR?", "SALIR",
                JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void comboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductoActionPerformed
        calcularPrecio();
    }//GEN-LAST:event_comboProductoActionPerformed

    private void spnCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCantidadStateChanged
        calcularPrecio();
    }//GEN-LAST:event_spnCantidadStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        factura venta = new factura();
        venta.setId(comboProducto.getSelectedIndex());
        venta.setNombre(comboProducto.getSelectedItem().toString());
        venta.setPrecio(precio);
        venta.setCantidad(cantidad);
        venta.setImporte(precio * cantidad);
        if(!buscarVenta(venta)){
            listaVentas.add(venta);
        }
        actualizarTabla();
        borrarFactura();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardarDatosEnArchivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        String total = ettotal.getText();
        D_Cajero cajero = new D_Cajero(new javax.swing.JFrame(), true, total);       
        cajero.setVisible(true);
    }//GEN-LAST:event_btnPagarActionPerformed

    public void borrarFactura() {
        precio = 0;
        cantidad = 1;
        comboProducto.setSelectedIndex(0);
        spnCantidad.setValue(1);
        calcularPrecio();
    }
    public boolean buscarVenta(factura nueva){
        for(factura venta: listaVentas){
            if(venta.getId()== nueva.getId()){
                int nuevaCantidad = venta.getCantidad() + nueva.getCantidad();
                venta.setCantidad(nuevaCantidad);
                venta.setImporte(venta.getPrecio()*nuevaCantidad);
                return true;
            }
        }
        return false;
    }

    public void calcularPrecio() {
        precio = precios[comboProducto.getSelectedIndex()];
        cantidad = Integer.parseInt(spnCantidad.getValue().toString());
        etPrecios.setText(cMoneda(precio));
        etPrecioImporte.setText(cMoneda(precio * cantidad));
    }

    public String cMoneda(double precio) {
        return "$" + Math.round(precio * 100.0) / 100.0 + "MXN";
    }

    public void actualizarTabla() {
        while (tablaOrden.getRowCount() > 0) {
            tablaOrden.removeRow(0);
        }
        double subtotal = 0;
        for (factura f : listaVentas) {
            
            Object x[] = new Object[4];
            x[0] = f.getNombre();
            x[1] = cMoneda(f.getPrecio());
            x[2] = f.getCantidad();
            x[3] = cMoneda(f.getImporte());
           subtotal+= f.getImporte();
           tablaOrden.addRow(x);
        }
        double total = subtotal;
        ettotal.setText(cMoneda(total));
        tablaProductos.setModel(tablaOrden);
    }
    
    private void guardarDatosEnArchivo() {
    try {
        if (listaVentas.isEmpty()) {
            throw new IllegalStateException("No se ha agregado ningún elemento,\n no es posible para el mesero tomar orden");
        }
        
        FileWriter archivo = new FileWriter("orden.txt", true);
        for (factura venta : listaVentas) {
            archivo.write(venta.getNombre() + "\t" + venta.getCantidad() + "\t" + venta.getImporte() + "\n");
        }
        archivo.close();
        JOptionPane.showMessageDialog(this, "La orden ha sido tomada por el mesero.", "Orden tomada", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar la orden en el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalStateException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRegresarOr;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JLabel etImporte;
    private javax.swing.JLabel etPrecio;
    private javax.swing.JLabel etPrecioImporte;
    private javax.swing.JLabel etPrecios;
    private javax.swing.JLabel ettotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrincipalOrden;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}