package Interfaces2;

import Dialogos.AgregarUser;
import Dialogos.Ayuda;
import Dialogos.EliminarUser;
import Dialogos.QuejasSugerencias;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.regex.*;


public class InterfazEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form InterfazEmpleados
     */
    public InterfazEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrncipal = new javax.swing.JPanel();
        etTitulo = new javax.swing.JLabel();
        EtNombre = new javax.swing.JLabel();
        TextNombreConsulta = new javax.swing.JTextField();
        EtHorario = new javax.swing.JLabel();
        etMostrarturno = new javax.swing.JLabel();
        EtCargo = new javax.swing.JLabel();
        etMostrarPuesto = new javax.swing.JLabel();
        EtId = new javax.swing.JLabel();
        textIdIngresar = new javax.swing.JTextField();
        etSueldo = new javax.swing.JLabel();
        etMostrarSueldo = new javax.swing.JLabel();
        REGRESAR = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        et_PrincipalEmpleados = new javax.swing.JLabel();
        Menu_Opciones = new javax.swing.JMenuBar();
        Op_Inicio = new javax.swing.JMenu();
        inicioOpcion = new javax.swing.JMenuItem();
        MenuOpcionir = new javax.swing.JMenuItem();
        SalioOpcion = new javax.swing.JMenuItem();
        Op_Usuarios = new javax.swing.JMenu();
        IngresarUser = new javax.swing.JMenuItem();
        EliminarUser = new javax.swing.JMenuItem();
        Op_info = new javax.swing.JMenu();
        QuejasSugerenciasOpcion = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        Opc_Soporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Empleados");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrncipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelPrncipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        etTitulo.setBackground(new java.awt.Color(204, 204, 204));
        etTitulo.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        etTitulo.setText("CONSULTAR INFORMACION DE EMPLEADOS");
        etTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etTitulo.setOpaque(true);
        getContentPane().add(etTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 810, 70));

        EtNombre.setBackground(new java.awt.Color(204, 204, 204));
        EtNombre.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EtNombre.setText("Nombre:");
        EtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EtNombre.setOpaque(true);
        getContentPane().add(EtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 50));
        getContentPane().add(TextNombreConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 470, 50));

        EtHorario.setBackground(new java.awt.Color(204, 204, 204));
        EtHorario.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EtHorario.setText("Turno:");
        EtHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EtHorario.setOpaque(true);
        getContentPane().add(EtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 90, 50));

        etMostrarturno.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etMostrarturno.setOpaque(true);
        getContentPane().add(etMostrarturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 150, 50));

        EtCargo.setBackground(new java.awt.Color(204, 204, 204));
        EtCargo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EtCargo.setText("Puesto:");
        EtCargo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EtCargo.setOpaque(true);
        getContentPane().add(EtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 100, 50));

        etMostrarPuesto.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etMostrarPuesto.setOpaque(true);
        getContentPane().add(etMostrarPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 160, 50));

        EtId.setBackground(new java.awt.Color(204, 204, 204));
        EtId.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        EtId.setText("ID:");
        EtId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EtId.setOpaque(true);
        getContentPane().add(EtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 40, 50));
        getContentPane().add(textIdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 50));

        etSueldo.setBackground(new java.awt.Color(204, 204, 204));
        etSueldo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        etSueldo.setText("Sueldo:");
        etSueldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etSueldo.setOpaque(true);
        getContentPane().add(etSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 100, 50));

        etMostrarSueldo.setBackground(new java.awt.Color(255, 255, 255));
        etMostrarSueldo.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        etMostrarSueldo.setOpaque(true);
        getContentPane().add(etMostrarSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 510, 50));

        REGRESAR.setBackground(new java.awt.Color(204, 204, 204));
        REGRESAR.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        REGRESAR.setText("REGRESAR");
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(REGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 120, 50));

        btnConsultar.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultar.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnConsultar.setText("CONSULTAR ");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 140, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 150, 50));

        et_PrincipalEmpleados.setBackground(new java.awt.Color(200, 173, 123));
        et_PrincipalEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        et_PrincipalEmpleados.setOpaque(true);
        getContentPane().add(et_PrincipalEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 910, 680));

        Menu_Opciones.setBackground(new java.awt.Color(204, 204, 204));
        Menu_Opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menu_Opciones.setOpaque(true);

        Op_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu_2976215.png"))); // NOI18N
        Op_Inicio.setText("Inicio");

        inicioOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagina-de-inicio.png"))); // NOI18N
        inicioOpcion.setText("Ir a Inicio");
        inicioOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioOpcionActionPerformed(evt);
            }
        });
        Op_Inicio.add(inicioOpcion);

        MenuOpcionir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu (1).png"))); // NOI18N
        MenuOpcionir.setText("Ir a Menú");
        MenuOpcionir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpcionirActionPerformed(evt);
            }
        });
        Op_Inicio.add(MenuOpcionir);

        SalioOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        SalioOpcion.setText("Salir");
        SalioOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalioOpcionActionPerformed(evt);
            }
        });
        Op_Inicio.add(SalioOpcion);

        Menu_Opciones.add(Op_Inicio);

        Op_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconUsuarios.png"))); // NOI18N
        Op_Usuarios.setText("Usuarios");
        Op_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op_UsuariosActionPerformed(evt);
            }
        });

        IngresarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario.png"))); // NOI18N
        IngresarUser.setText("Ingresar");
        IngresarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarUserActionPerformed(evt);
            }
        });
        Op_Usuarios.add(IngresarUser);

        EliminarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-amigo.png"))); // NOI18N
        EliminarUser.setText("Eliminar");
        EliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUserActionPerformed(evt);
            }
        });
        Op_Usuarios.add(EliminarUser);

        Menu_Opciones.add(Op_Usuarios);

        Op_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informacion.png"))); // NOI18N
        Op_info.setText("Informacion");

        QuejasSugerenciasOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/quejasSugIcon.png"))); // NOI18N
        QuejasSugerenciasOpcion.setText("Quejas / sugerencias");
        QuejasSugerenciasOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuejasSugerenciasOpcionActionPerformed(evt);
            }
        });
        Op_info.add(QuejasSugerenciasOpcion);

        Menu_Opciones.add(Op_info);

        Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pregunta.png"))); // NOI18N
        Ayuda.setText("Ayuda");

        Opc_Soporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apoyo-tecnico.png"))); // NOI18N
        Opc_Soporte.setText("Soporte");
        Opc_Soporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opc_SoporteActionPerformed(evt);
            }
        });
        Ayuda.add(Opc_Soporte);

        Menu_Opciones.add(Ayuda);

        setJMenuBar(Menu_Opciones);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
        InterfazRestaurante2 regresar = new InterfazRestaurante2();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_REGRESARActionPerformed

    private void IngresarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarUserActionPerformed
        AgregarUser agregar = new AgregarUser(this,true);
        agregar.setVisible(true);
    }//GEN-LAST:event_IngresarUserActionPerformed

    private void Op_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Op_UsuariosActionPerformed

    }//GEN-LAST:event_Op_UsuariosActionPerformed

    private void EliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUserActionPerformed
        EliminarUser eliminar = new EliminarUser(this, true);
        eliminar.setVisible(true);
    }//GEN-LAST:event_EliminarUserActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(this,"¿SEGURO QUE QUIERES SALIR?","SALIR"
                ,JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
        System.exit(0);
        }    
    }//GEN-LAST:event_formWindowClosing

    private void inicioOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioOpcionActionPerformed
        InterfazRestaurante2 regresar = new InterfazRestaurante2();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inicioOpcionActionPerformed

    private void MenuOpcionirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpcionirActionPerformed
        Menu irMenu = new Menu();
        irMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuOpcionirActionPerformed

    private void SalioOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalioOpcionActionPerformed
        if(JOptionPane.showConfirmDialog(this,"¿SEGURO QUE QUIERES SALIR?","SALIR"
                ,JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
        System.exit(0);
        }    
    }//GEN-LAST:event_SalioOpcionActionPerformed

    private void Opc_SoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opc_SoporteActionPerformed
        Ayuda soporte = new Ayuda(this, true);
        soporte.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Opc_SoporteActionPerformed

    private void QuejasSugerenciasOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuejasSugerenciasOpcionActionPerformed
        QuejasSugerencias qys = new QuejasSugerencias(this, true);
        qys.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QuejasSugerenciasOpcionActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
         // Obtener el nombre y la ID ingresados en los JTextField
    String nombreBuscado = TextNombreConsulta.getText();
    String idBuscada = textIdIngresar.getText();
    
    if(nombreBuscado.isEmpty() || idBuscada.isEmpty()){
        JOptionPane.showMessageDialog(this, "Por favor llene los campos solicitados");
    }
    
    // Intentar encontrar el empleado en el archivo
    try {
        FileReader fr = new FileReader("empleados.txt");
        BufferedReader br = new BufferedReader(fr);
        String linea;
        boolean encontrado = false;

        while ((linea = br.readLine()) != null) {
            // Verificar si la línea contiene el nombre y la ID buscados
            if (linea.contains("nombre=" + nombreBuscado) && linea.contains("idEmpleado=" + idBuscada)) {
                // Extraer el turno, puesto y salario de la línea
                String turno = obtenerValor(linea, "Turno Laboral");
                String puesto = obtenerValor(linea, "puesto");
                String salario = obtenerSalario(linea);

                // Mostrar la información encontrada
                mostrarInformacion(turno, puesto, salario);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            // Mostrar un mensaje si el empleado no se encuentra
            JOptionPane.showMessageDialog(null, "No se encontró al empleado.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        br.close();
        fr.close();
    } catch (IOException e) {
        // Manejar cualquier error de lectura del archivo
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al leer el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TextNombreConsulta.setText("");
        textIdIngresar.setText("");
        etMostrarturno.setText("");
        etMostrarPuesto.setText("");
        etMostrarSueldo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    // Método para extraer el valor de una clave en una línea
    private String obtenerValor(String linea, String clave) {
        int inicio = linea.indexOf(clave + "=") + clave.length() + 1;
        int fin = linea.indexOf(",", inicio);
        if (fin == -1) {
            fin = linea.length() - 1;
        }
        return linea.substring(inicio, fin);
    }
    
   

// Método específico para obtener el salario de una línea utilizando expresiones regulares
private String obtenerSalario(String linea) {
    // Definir el patrón para encontrar el salario
    Pattern patronSalario = Pattern.compile("\\$([0-9,.]+)"); // Busca un signo de dólar seguido de uno o más dígitos, puntos o comas
    Matcher matcher = patronSalario.matcher(linea);

    // Buscar el salario utilizando el patrón
    if (matcher.find()) {
        // Extraer el salario y eliminar caracteres no numéricos
        String salarioConSimbolo = matcher.group(1);
        String salarioNumerico = salarioConSimbolo.replaceAll("[^0-9]", "");
        return salarioNumerico; // Devuelve el valor numérico del salario
    } else {
        return ""; // Devuelve una cadena vacía si no se encuentra el salario
    }
}



    // Método para mostrar la información encontrada
    private void mostrarInformacion(String turno, String puesto, String salario) {
        // Mostrar la información en JTextFields o JLabels
        etMostrarturno.setText(turno);
        etMostrarPuesto.setText(puesto);
        etMostrarSueldo.setText(salario);
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem EliminarUser;
    private javax.swing.JLabel EtCargo;
    private javax.swing.JLabel EtHorario;
    private javax.swing.JLabel EtId;
    private javax.swing.JLabel EtNombre;
    private javax.swing.JMenuItem IngresarUser;
    private javax.swing.JMenuItem MenuOpcionir;
    private javax.swing.JMenuBar Menu_Opciones;
    private javax.swing.JMenu Op_Inicio;
    private javax.swing.JMenu Op_Usuarios;
    private javax.swing.JMenu Op_info;
    private javax.swing.JMenuItem Opc_Soporte;
    private javax.swing.JMenuItem QuejasSugerenciasOpcion;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JMenuItem SalioOpcion;
    private javax.swing.JTextField TextNombreConsulta;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel etMostrarPuesto;
    private javax.swing.JLabel etMostrarSueldo;
    private javax.swing.JLabel etMostrarturno;
    private javax.swing.JLabel etSueldo;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JLabel et_PrincipalEmpleados;
    private javax.swing.JMenuItem inicioOpcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelPrncipal;
    private javax.swing.JTextField textIdIngresar;
    // End of variables declaration//GEN-END:variables
}
