package Interfaces2;

import javax.swing.JOptionPane;

/**
 *
 * @author carmi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalMenu = new javax.swing.JPanel();
        Et_Menu = new javax.swing.JLabel();
        Et_img_Pizza = new javax.swing.JLabel();
        JscrollPizzas = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Et_NamePizza = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        Et_BurgerImg = new javax.swing.JLabel();
        jScrollHamburguesa = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        Et_NameBurguer = new javax.swing.JLabel();
        Et_namepapas = new javax.swing.JLabel();
        Et_NamePapas = new javax.swing.JLabel();
        jScrollPapas = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        Et_NameBebidas = new javax.swing.JLabel();
        et_imgBebidas = new javax.swing.JLabel();
        jScrollBebidas = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        et_imgCombos = new javax.swing.JLabel();
        Et_NameCombos = new javax.swing.JLabel();
        jScrollCombos = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        BtnIrOrden = new javax.swing.JButton();
        Et_menufondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MENÚ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipalMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanelPrincipalMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Et_Menu.setBackground(new java.awt.Color(200, 173, 123));
        Et_Menu.setFont(new java.awt.Font("Showcard Gothic", 2, 48)); // NOI18N
        Et_Menu.setText("MENÚ");
        Et_Menu.setOpaque(true);
        getContentPane().add(Et_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 170, 80));

        Et_img_Pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pizza.jpg"))); // NOI18N
        getContentPane().add(Et_img_Pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 170));

        jList1.setBackground(new java.awt.Color(200, 173, 123));
        jList1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pizza Peperoni, $100.00", "Pizza Hawaiana,$130.00", "Pizza Queso, $89.00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JscrollPizzas.setViewportView(jList1);

        getContentPane().add(JscrollPizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 194, 73));

        Et_NamePizza.setBackground(new java.awt.Color(200, 173, 123));
        Et_NamePizza.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Et_NamePizza.setText("PIZZAS");
        Et_NamePizza.setOpaque(true);
        getContentPane().add(Et_NamePizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 130, 40));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 130, 60));

        Et_BurgerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hamburguesa.Etpng.jpg"))); // NOI18N
        getContentPane().add(Et_BurgerImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 160));

        jList3.setBackground(new java.awt.Color(200, 173, 123));
        jList3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hamburguesa Sencilla,$36.00", "Hamburguesa Doble,$60.00", "Hamburguesa Hawaiana,$45.00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.setDragEnabled(true);
        jScrollHamburguesa.setViewportView(jList3);

        getContentPane().add(jScrollHamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, 73));

        Et_NameBurguer.setBackground(new java.awt.Color(200, 173, 123));
        Et_NameBurguer.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Et_NameBurguer.setText("HAMBURGUESAS");
        Et_NameBurguer.setOpaque(true);
        getContentPane().add(Et_NameBurguer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 200, 40));

        Et_namepapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/papaset.jpg"))); // NOI18N
        getContentPane().add(Et_namepapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, 190));

        Et_NamePapas.setBackground(new java.awt.Color(200, 173, 123));
        Et_NamePapas.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Et_NamePapas.setText("PAPAS FRITAS");
        Et_NamePapas.setOpaque(true);
        getContentPane().add(Et_NamePapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 200, 40));

        jScrollPapas.setBackground(new java.awt.Color(200, 173, 123));

        jList4.setBackground(new java.awt.Color(200, 173, 123));
        jList4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Papas Fritas Grandes,$25.00", "Papas Fritas Medianas,$15.00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPapas.setViewportView(jList4);

        getContentPane().add(jScrollPapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 194, 63));

        Et_NameBebidas.setBackground(new java.awt.Color(200, 173, 123));
        Et_NameBebidas.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Et_NameBebidas.setText("BEBIDAS");
        Et_NameBebidas.setOpaque(true);
        getContentPane().add(Et_NameBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 130, 40));

        et_imgBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasIcon.jpg"))); // NOI18N
        getContentPane().add(et_imgBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, 150));

        jScrollBebidas.setBackground(new java.awt.Color(200, 173, 123));

        jList5.setBackground(new java.awt.Color(200, 173, 123));
        jList5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Refresco,$18.00", "Malteada,$35.00", "Agua sabor 1L,$12.00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollBebidas.setViewportView(jList5);

        getContentPane().add(jScrollBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 194, 79));

        et_imgCombos.setBackground(new java.awt.Color(200, 173, 123));
        et_imgCombos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combosicon.png"))); // NOI18N
        getContentPane().add(et_imgCombos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 280, 160));

        Et_NameCombos.setBackground(new java.awt.Color(200, 173, 123));
        Et_NameCombos.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Et_NameCombos.setText("combos");
        Et_NameCombos.setOpaque(true);
        getContentPane().add(Et_NameCombos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 120, 50));

        jScrollCombos.setBackground(new java.awt.Color(200, 173, 123));

        jList6.setBackground(new java.awt.Color(200, 173, 123));
        jList6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "COMBO CLASICO: ", "Hamburguesa sencilla + refresco y papas medianas $60.00", "COMBO TRIO:", "Pizza Peperoni + 3 refrescos + papas grandes $145.00", "COMBO FAMILIAR", "1 Pizza de queso + 2 Hamburguesa doble +2 Malteadas Y Papas Grandes $240.00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollCombos.setViewportView(jList6);

        getContentPane().add(jScrollCombos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 470, 140));

        BtnIrOrden.setBackground(new java.awt.Color(204, 204, 204));
        BtnIrOrden.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnIrOrden.setText("ORDEN");
        BtnIrOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIrOrdenMouseClicked(evt);
            }
        });
        BtnIrOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIrOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIrOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 710, 140, 60));

        Et_menufondo.setBackground(new java.awt.Color(200, 173, 123));
        Et_menufondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInterfazMenu.jpg"))); // NOI18N
        Et_menufondo.setOpaque(true);
        getContentPane().add(Et_menufondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 960, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        InterfazRestaurante2 restaurante = new InterfazRestaurante2();
        restaurante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        InterfazRestaurante2 restaurante = new InterfazRestaurante2();
        restaurante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         if(JOptionPane.showConfirmDialog(this,"¿SEGURO QUE QUIERES SALIR?","SALIR"
                ,JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
        System.exit(0);
        }   
    }//GEN-LAST:event_formWindowClosing

    private void BtnIrOrdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIrOrdenMouseClicked
        interfazOrden2 orden = new interfazOrden2();
        orden.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnIrOrdenMouseClicked

    private void BtnIrOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIrOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIrOrdenActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIrOrden;
    private javax.swing.JLabel Et_BurgerImg;
    private javax.swing.JLabel Et_Menu;
    private javax.swing.JLabel Et_NameBebidas;
    private javax.swing.JLabel Et_NameBurguer;
    private javax.swing.JLabel Et_NameCombos;
    private javax.swing.JLabel Et_NamePapas;
    private javax.swing.JLabel Et_NamePizza;
    private javax.swing.JLabel Et_img_Pizza;
    private javax.swing.JLabel Et_menufondo;
    private javax.swing.JLabel Et_namepapas;
    private javax.swing.JScrollPane JscrollPizzas;
    private javax.swing.JPanel PanelPrincipalMenu;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel et_imgBebidas;
    private javax.swing.JLabel et_imgCombos;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JScrollPane jScrollBebidas;
    private javax.swing.JScrollPane jScrollCombos;
    private javax.swing.JScrollPane jScrollHamburguesa;
    private javax.swing.JScrollPane jScrollPapas;
    // End of variables declaration//GEN-END:variables
}
