
package Dialogos;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author carmi
 */
public class EliminarUser extends javax.swing.JDialog {

    /**
     * Creates new form EliminarUser
     */
    public EliminarUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalEliminar = new javax.swing.JPanel();
        etTitulo = new javax.swing.JLabel();
        etNombre = new javax.swing.JLabel();
        jTextNombreElminar = new javax.swing.JTextField();
        etIdUsuarioEliminar = new javax.swing.JLabel();
        jTextIdEliminar = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnEliminarUser = new javax.swing.JButton();
        etFondoEliminar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipalEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanelPrincipalEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        etTitulo.setBackground(new java.awt.Color(204, 204, 204));
        etTitulo.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        etTitulo.setText("ELIMINAR USUARIO ");
        etTitulo.setOpaque(true);
        getContentPane().add(etTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 12, 270, 60));

        etNombre.setBackground(new java.awt.Color(204, 204, 204));
        etNombre.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        etNombre.setText("Ingrese el nombre del usuario a eliminar: ");
        etNombre.setOpaque(true);
        getContentPane().add(etNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 50));
        getContentPane().add(jTextNombreElminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 280, 50));

        etIdUsuarioEliminar.setBackground(new java.awt.Color(204, 204, 204));
        etIdUsuarioEliminar.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        etIdUsuarioEliminar.setText("Ingrese el ID del usuario a eliminar: ");
        etIdUsuarioEliminar.setOpaque(true);
        getContentPane().add(etIdUsuarioEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 310, 40));
        getContentPane().add(jTextIdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 180, 40));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 130, 50));

        btnEliminarUser.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarUser.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        btnEliminarUser.setText("ELIMINAR USUARIO");
        btnEliminarUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarUser.setOpaque(true);
        btnEliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 220, 50));

        etFondoEliminar.setBackground(new java.awt.Color(200, 173, 123));
        etFondoEliminar.setOpaque(true);
        getContentPane().add(etFondoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked

    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUserActionPerformed
        String nombreUserEliminar = jTextNombreElminar.getText();
        String idUserEliminar = jTextIdEliminar.getText();
    
        // Verificar si se ingresó un nombre y un ID
        if (nombreUserEliminar.isEmpty() || idUserEliminar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre y un ID para buscar y eliminar al usuario.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Mostrar un cuadro de diálogo de confirmación
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar al usuario?", "Confirmación", 
                JOptionPane.YES_NO_OPTION);

        // Verificar la respuesta del usuario
        if (respuesta == JOptionPane.YES_OPTION) {
        // El usuario confirmó la eliminación, proceder con la eliminación
        boolean eliminado = eliminarUsuario(nombreUserEliminar, idUserEliminar);
        
        // Verificar si el usuario fue eliminado correctamente
        if (eliminado) {
            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
            // Limpiar los campos de texto y los mensajes de los campos
            limpiarCampos();
        } else {
            // Mostrar un mensaje de que el usuario no se encontró
            JOptionPane.showMessageDialog(this, "No se encontró al usuario con el nombre y el ID proporcionados.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        } else if (respuesta == JOptionPane.NO_OPTION) {
        // El usuario canceló la eliminación
        JOptionPane.showMessageDialog(this, "Operación cancelada por el usuario.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_btnEliminarUserActionPerformed

    private boolean eliminarUsuario(String nombreUsuario, String idUsuario) {
        // Crear una lista para almacenar las líneas del archivo temporales
    List<String> lineasTemporales = new ArrayList<>();

    // Definir el nombre del archivo
    String nombreArchivo = "empleados.txt";

    boolean encontrado = false;

    try {
        // Abrir el archivo para lectura
        BufferedReader br = new BufferedReader(new FileReader(nombreArchivo));
        String linea;

        // Leer cada línea del archivo
        while ((linea = br.readLine()) != null) {
            // Buscar la posición del nombre y el ID en la línea
            int posNombre = linea.indexOf("nombre=") + 7; // Ajuste del índice para eliminar el apóstrofe
            int posId = linea.indexOf("idEmpleado=") + 11;

            // Extraer el nombre y el ID de la línea
            String nombreUserArchivo = linea.substring(posNombre, linea.indexOf(",", posNombre));
            String idArchivo = linea.substring(posId, linea.indexOf(",", posId));

            // Verificar si el nombre y el ID coinciden
            if (nombreUserArchivo.trim().equals(nombreUsuario) && idArchivo.trim().equals(idUsuario)) {
                // Si hay coincidencia, marcar como encontrado y no agregar esta línea a la lista temporal (eliminación)
                encontrado = true;
                continue;
            }

            // Agregar la línea a la lista temporal
            lineasTemporales.add(linea);
        }

        // Cerrar el BufferedReader
        br.close();

        // Si el usuario no fue encontrado, devolver false
        if (!encontrado) {
            return false;
        }

        // Abrir el archivo para escritura
        BufferedWriter bw = new BufferedWriter(new FileWriter(nombreArchivo));

        // Escribir todas las líneas no eliminadas en el archivo
        for (String lineaTemporal : lineasTemporales) {
            bw.write(lineaTemporal);
            bw.newLine();
        }

        // Cerrar el BufferedWriter
        bw.close();

        // Devolver true para indicar que el usuario fue eliminado correctamente
        return true;

    } catch (IOException e) {
        // Mostrar un mensaje de error si ocurre un problema al leer o escribir en el archivo
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al eliminar el usuario", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }        
    }
    
    private void limpiarCampos() {
    jTextNombreElminar.setText("");
    jTextIdEliminar.setText("");
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipalEliminar;
    private javax.swing.JButton btnEliminarUser;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel etFondoEliminar;
    private javax.swing.JLabel etIdUsuarioEliminar;
    private javax.swing.JLabel etNombre;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JTextField jTextIdEliminar;
    private javax.swing.JTextField jTextNombreElminar;
    // End of variables declaration//GEN-END:variables
}
